In [17]:
import pandas as pd
data = pd.read_csv(r'C:\Users\hanao\Downloads\headline-hoax-detector\ds-role\dataset\raw\dewan_pers.csv')

In [18]:
data.head()

,nama_media,jenis_media,penanggung_jawab,pemimpin_redaksi,badan_hukum,provinsi,alamat,telp,email,website,status,tanggal
0,NaN,Cetak\r\nRadio\r\nTelevisi\r\nSiber,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Jabungtoday.com,Siber,Hendry Nursal,Hendry Nursal,Media Putra Jabung,Jambi,"Jl.Ternate, Lrg.Puspon, RT 03 No 49 Simpang Su...",081313024411,jabungtoday@gmail.com,https://jabungtoday.com/,Terverifikasi Administratif dan Faktual,2026-04-23
2,Akurat.co,Siber,Aldi Gultom,Aldi Gultom,Akurat Sentra Media,DKI Jakarta,Jl. Tentara Pelajar Rukan Permata Senayan Blok...,02157941110,akuratco@gmail.com,https://akurat.co/,Terverifikasi Administratif dan Faktual,2026-04-23
3,bentengsumbar.com,Siber,Zamri Yahya,Zamri Yahya,Benteng Sumbar Persada,Sumatera Barat,Jalan Piai Tangah RT.001/RW.001 Kelurahan Piai...,0751779490,bentengsumbar@gmail.com,https://www.bentengsumbar.com/,Terverifikasi Administratif dan Faktual,2026-04-23
4,Tribun Pekanbaru,Cetak,Erwin Ardian,Erwin Ardian,Riau Media Grafika,Riau,Jl. H Imam Munandar No.383 RT01 RW04 Tangkeran...,076136345,hrtribunpekanbaru@gmail.com,www.tribunpekanbaru.com,Terverifikasi Administratif dan Faktual,2026-04-23

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2640 entries, 0 to 2639
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nama_media        2400 non-null   object
 1   jenis_media       2640 non-null   object
 2   penanggung_jawab  1766 non-null   object
 3   pemimpin_redaksi  1766 non-null   object
 4   badan_hukum       2396 non-null   object
 5   provinsi          2395 non-null   object
 6   alamat            2373 non-null   object
 7   telp              1898 non-null   object
 8   email             1849 non-null   object
 9   website           1711 non-null   object
 10  status            2400 non-null   object
 11  tanggal           2400 non-null   object
dtypes: object(12)
memory usage: 247.6+ KB

In [20]:
data['jenis_media'].unique()

array(['Cetak\r\nRadio\r\nTelevisi\r\nSiber', 'Siber', 'Cetak',
       'Televisi', 'Radio'], dtype=object)

In [21]:
data = data[data['jenis_media'] == 'Siber']
data.head()

,nama_media,jenis_media,penanggung_jawab,pemimpin_redaksi,badan_hukum,provinsi,alamat,telp,email,website,status,tanggal
1,Jabungtoday.com,Siber,Hendry Nursal,Hendry Nursal,Media Putra Jabung,Jambi,"Jl.Ternate, Lrg.Puspon, RT 03 No 49 Simpang Su...",081313024411,jabungtoday@gmail.com,https://jabungtoday.com/,Terverifikasi Administratif dan Faktual,2026-04-23
2,Akurat.co,Siber,Aldi Gultom,Aldi Gultom,Akurat Sentra Media,DKI Jakarta,Jl. Tentara Pelajar Rukan Permata Senayan Blok...,02157941110,akuratco@gmail.com,https://akurat.co/,Terverifikasi Administratif dan Faktual,2026-04-23
3,bentengsumbar.com,Siber,Zamri Yahya,Zamri Yahya,Benteng Sumbar Persada,Sumatera Barat,Jalan Piai Tangah RT.001/RW.001 Kelurahan Piai...,0751779490,bentengsumbar@gmail.com,https://www.bentengsumbar.com/,Terverifikasi Administratif dan Faktual,2026-04-23
5,niaga.asia,Siber,Intoniswan,Intoniswan,Kaltim prima multi media,Kalimantan Timur,Jl Siradj Salman Komplek Ruko Grand Mahakam Bl...,05412082956,niagaredaksi@gmail.com,https://www.niaga.asia/,Terverifikasi Administratif dan Faktual,2026-04-23
6,mediaindonesia.com,Siber,Abdul Kohar,Abdul Kohar,Citra Medianusa Purnama,DKI Jakarta,"Jl. Pilar Mas Raya Kav A-D Kedoya Selatan, Keb...",0215821303,redaksi.micom@mediaindonesia.com,www.mediaindonesia.com,Terverifikasi Administratif dan Faktual,2026-04-23

In [22]:
data.shape

(1295, 12)

In [23]:
data['status'].unique()

array(['Terverifikasi Administratif dan Faktual',
       'Terverifikasi Administratif',
       'Terverifikasi Administrasi dan Faktual',
       'Terverifikasi Administrasi'], dtype=object)

In [24]:
data = data[data['status'] == 'Terverifikasi Administratif dan Faktual']
data.head()

,nama_media,jenis_media,penanggung_jawab,pemimpin_redaksi,badan_hukum,provinsi,alamat,telp,email,website,status,tanggal
1,Jabungtoday.com,Siber,Hendry Nursal,Hendry Nursal,Media Putra Jabung,Jambi,"Jl.Ternate, Lrg.Puspon, RT 03 No 49 Simpang Su...",081313024411,jabungtoday@gmail.com,https://jabungtoday.com/,Terverifikasi Administratif dan Faktual,2026-04-23
2,Akurat.co,Siber,Aldi Gultom,Aldi Gultom,Akurat Sentra Media,DKI Jakarta,Jl. Tentara Pelajar Rukan Permata Senayan Blok...,02157941110,akuratco@gmail.com,https://akurat.co/,Terverifikasi Administratif dan Faktual,2026-04-23
3,bentengsumbar.com,Siber,Zamri Yahya,Zamri Yahya,Benteng Sumbar Persada,Sumatera Barat,Jalan Piai Tangah RT.001/RW.001 Kelurahan Piai...,0751779490,bentengsumbar@gmail.com,https://www.bentengsumbar.com/,Terverifikasi Administratif dan Faktual,2026-04-23
5,niaga.asia,Siber,Intoniswan,Intoniswan,Kaltim prima multi media,Kalimantan Timur,Jl Siradj Salman Komplek Ruko Grand Mahakam Bl...,05412082956,niagaredaksi@gmail.com,https://www.niaga.asia/,Terverifikasi Administratif dan Faktual,2026-04-23
6,mediaindonesia.com,Siber,Abdul Kohar,Abdul Kohar,Citra Medianusa Purnama,DKI Jakarta,"Jl. Pilar Mas Raya Kav A-D Kedoya Selatan, Keb...",0215821303,redaksi.micom@mediaindonesia.com,www.mediaindonesia.com,Terverifikasi Administratif dan Faktual,2026-04-23

In [25]:
data.shape

(933, 12)

In [27]:
data = data[['nama_media', 'website']]
data.head()

           nama_media                         website
1     Jabungtoday.com        https://jabungtoday.com/
2           Akurat.co              https://akurat.co/
3   bentengsumbar.com  https://www.bentengsumbar.com/
5          niaga.asia         https://www.niaga.asia/
6  mediaindonesia.com          www.mediaindonesia.com

In [28]:
data.isnull().sum()

nama_media     0
website       58
dtype: int64

In [29]:
data = data.dropna()
print(f"Shape after dropping NaN values: {data.shape}")

Shape after dropping NaN values: (875, 2)

In [30]:
data.duplicated().sum()

0

In [31]:
data = data.drop_duplicates()
print(f"Shape after dropping duplicate: {data.shape}")

Shape after dropping duplicate: (875, 2)

In [32]:
# Simpan hanya kolom yang diperlukan untuk training
data.to_csv(r'C:\Users\hanao\Downloads\headline-hoax-detector\ds-role\dataset\final\final-pers.csv', index=False)
print("Data berhasil disimpan!")

Data berhasil disimpan!